/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author samue
 */
public class OptionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form optionsFrame
     */
    public OptionsFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        imageToolBar = new javax.swing.JToolBar();
        threshSlider = new javax.swing.JSlider();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        makeBWButton = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        FileToolBar = new javax.swing.JToolBar();
        openFileButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        saveFileButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        resetFileButton = new javax.swing.JButton();
        invertColorButton = new javax.swing.JButton();
        applyRefinementButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        imageToolBar.setFloatable(false);
        imageToolBar.setRollover(true);

        threshSlider.setMaximum(255);
        threshSlider.setToolTipText("Limiar");
        threshSlider.setValue(0);
        threshSlider.setBorder(javax.swing.BorderFactory.createTitledBorder("Limiar do preto-e-branco"));
        threshSlider.setEnabled(false);
        imageToolBar.add(threshSlider);
        imageToolBar.add(jSeparator3);
        imageToolBar.add(jSeparator2);

        makeBWButton.setText("Fazer Preto-e-Branco");
        makeBWButton.setToolTipText("Tranforma a Imagem em Preto-e-Branco");
        makeBWButton.setEnabled(false);
        makeBWButton.setFocusPainted(false);
        makeBWButton.setFocusable(false);
        makeBWButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        makeBWButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        imageToolBar.add(makeBWButton);

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visualizar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panel.setAutoscrolls(true);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
                panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 513, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
                panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 216, Short.MAX_VALUE)
        );

        FileToolBar.setFloatable(false);
        FileToolBar.setRollover(true);

        openFileButton.setText("Abrir Arquivo");
        openFileButton.setToolTipText("Abre uma nova imagem");
        openFileButton.setFocusable(false);
        openFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openFileButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        FileToolBar.add(openFileButton);
        FileToolBar.add(jSeparator4);

        saveFileButton.setText("Salvar Arquivo");
        saveFileButton.setToolTipText("Salva como um novo arquivo");
        saveFileButton.setEnabled(false);
        saveFileButton.setFocusable(false);
        saveFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveFileButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        FileToolBar.add(saveFileButton);
        FileToolBar.add(jSeparator1);

        resetFileButton.setText("Restaurar Original");
        resetFileButton.setToolTipText("Restaura a imagem orininal");
        resetFileButton.setEnabled(false);
        resetFileButton.setFocusable(false);
        resetFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resetFileButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        FileToolBar.add(resetFileButton);

        invertColorButton.setText("Inverter Cores");
        invertColorButton.setFocusable(false);
        invertColorButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        invertColorButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        invertColorButton.setEnabled(false);
        FileToolBar.add(invertColorButton);

        applyRefinementButton.setText("Aplicar Afinamento de Zhang-Suen");
        applyRefinementButton.setToolTipText("Aplica o Afinamento");
        applyRefinementButton.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(FileToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(applyRefinementButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(imageToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imageToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FileToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(applyRefinementButton)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void applyRefinementButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    public javax.swing.JToolBar FileToolBar;
    public javax.swing.JButton applyRefinementButton;
    public javax.swing.JToolBar imageToolBar;
    public javax.swing.JButton invertColorButton;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    public javax.swing.JButton makeBWButton;
    public javax.swing.JButton openFileButton;
    public javax.swing.JPanel panel;
    public javax.swing.JButton resetFileButton;
    public javax.swing.JButton saveFileButton;
    public javax.swing.JSlider threshSlider;
    // End of variables declaration
}
